cmd/livecheck: require "formula" (#1315)
Fix:
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/dawidd6/homebrew-test/Formula/test-formula-url.rb:2:in `<class:TestFormulaUrl>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/dawidd6/homebrew-test/Formula/test-formula-url.rb:1:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/extend/formulary.rb:22:in `module_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/extend/formulary.rb:22:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:64:in `load_formula_from_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:149:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:294:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:139:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:135:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:284:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:344:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:21:in `block in to_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:20:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:20:in `to_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/args.rb:60:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-livecheck/cmd/livecheck.rb:94:in `livecheck'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: dawidd6/test/test-formula-url: undefined method `desc' for #<Class:0x000000000328e300>
```

After latest changes in `brew`:
https://github.com/Homebrew/brew/pull/8382