Fix 'undefined method .exist?' error for lc_path
- Check that `lc_path` is defined before calling `.exist?` on it.
- Also fix some inconsistent indentation.

Before:

```
$ brew livecheck gnuradio
Error: undefined method `exist?' for nil:NilClass
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/extend/formulary.rb:22:in `load_formula'
```
After:

```
$ brew livecheck gnuradio
gnuradio (guessed) : 3.7.13.4 ==> 3.8tech-preview
```